trigger:
- main

pool: Default

stages:
  - stage: dev
    jobs:
      - job : deploy
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '1.5.0' 
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'aciserviceconnection'
              backendAzureRmResourceGroupName: 'bharathrs'
              backendAzureRmStorageAccountName: 'manideepstg'
              backendAzureRmContainerName: 'mcontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'aciserviceconnection'
